server:
  port: 8080
  read_timeout: 30s
  write_timeout: 30s
  max_header_bytes: 1048576
  shutdown_timeout: 5s

providers:
  openai:
    type: openai
    model: gpt-4o-mini
    api_key: ${OPENAI_API_KEY}
  anthropic:
    type: anthropic
    model: claude-3.5-haiku-latest
    api_key: ${ANTHROPIC_API_KEY}
  ollama:
    type: ollama
    model: llama3
    api_key: ""

# Order of provider preference for failover
provider_preference:
  - openai
  - anthropic
  - ollama

logging:
  level: info
  format: json

metrics:
  enabled: true
  prometheus:
    enabled: true
