title: "Hapax"
description: "The reliability layer between your code and LLM providers"
remote_theme: "just-the-docs/just-the-docs"

# Theme and Navigation
color_scheme: "dark"
nav_spacing: "normal"
heading_anchors: true
back_to_top: true
back_to_top_text: "Back to top"

# Theme Overrides
color_scheme: "dark"
custom_css: true
custom_css_path: "/assets/css/custom.css"

# Typography and Spacing
spacing_unit: 2
font_size: "16px"
content_width: "900px"
typographic_spacing: true

# Heading Styles
heading_spacing: 2.5
h1_size: "3rem"
h2_size: "2.5rem"
h3_size: "1.75rem"
h4_size: "1.25rem"

# Text Styles
body_line_height: 1.8
body_font_family: "system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif"
mono_font_family: "'SFMono-Regular', Consolas, 'Liberation Mono', Menlo, Courier, monospace"

# Search Configuration
search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 5
  tokenizer_separator: "/[\\s/]+/"
  rel_url: true
  button: false

# Code and Content
enable_copy_code_button: true
code_block_padding: "1.5rem"
code_font_size: "0.95em"

# Callouts for Important Information
callouts:
  note:
    title: "Note"
    color: "blue"
  important:
    title: "Important"
    color: "purple"
  warning:
    title: "Warning"
    color: "red"
  tip:
    title: "Tip"
    color: "green"
  security:
    title: "Security"
    color: "yellow"

# External Links
aux_links:
  "GitHub": ["//github.com/teilomillet/hapax"]
aux_links_new_tab: true

# License
footer_content: "Licensed under Apache License, Version 2.0."

# Additional Styles
callouts_opacity: 1
callouts_padding: "1.5rem"
table_font_size: "0.95em"
nav_font_size: "1rem"
sidebar_width: "280px"